name: Test4
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Test step
        env:
          FEISHU_APP_ID: \${{ secrets.FEISHU_APP_ID }}
          FEISHU_APP_SECRET: \${{ secrets.FEISHU_APP_SECRET }}
        run: echo "Hello"
